-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 26, 2015 at 03:04 AM
-- Server version: 5.5.41-cll-lve
-- PHP Version: 5.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `tourepedia1`
--

-- --------------------------------------------------------

--
-- Table structure for table `attractions`
--

CREATE TABLE IF NOT EXISTS `attractions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `attraction_name` varchar(200) NOT NULL,
  `places_id` int(11) NOT NULL,
  `attraction_about` varchar(500) NOT NULL,
  `attraction_timeSpan` varchar(200) NOT NULL,
  `attraction_cost` varchar(200) NOT NULL,
  `attraction_image` varchar(200) NOT NULL,
  `attraction_postalCode` varchar(20) NOT NULL,
  `attraction_overall_rating` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=137 ;

--
-- Dumping data for table `attractions`
--

INSERT INTO `attractions` (`id`, `attraction_name`, `places_id`, `attraction_about`, `attraction_timeSpan`, `attraction_cost`, `attraction_image`, `attraction_postalCode`, `attraction_overall_rating`) VALUES
(1, 'Beas Kung', 1, 'Considered to be the birthplace of River Beas, Beas Kund is as breathtaking as it is astonishing. It is said sage Rishi Vyas took his daily bath here. The igloo like stone formation at the kund is the starting point for a number of treks, including Friendship and Hanuman Tibba peaks.', '06:00 AM - 06:00 PM', '', 'assets/images/manali/beas-kund/img1.jpg', '', 0),
(2, 'Hadimba Temple', 1, 'It is assumed that The Hidimba Devi temple is built around a cave where Hidimba performed meditation. The tower consists of three square roofs covered with timber tiles and a fourth brass cone-shaped roof at the top. The earth goddess Durga forms the theme of the main door carvings.The temple base is made out of whitewashed, mud-covered stonework.\nNOTE: This is a religious site. Please respect that fact and do not dress inappropriately.\n', '08:00 AM - 06:00 AM', '', 'assets/images/manali/hadimba-temple/img1.jpg', '', 0),
(3, 'Kullu', 1, 'Kullu is a broad open valley formed by the Beas river between Manali and Largi. This valley is famous for its temples, beauty and its majestic hills covered with Pine and Deodar Forest and sprawling Apple Orchards. Kullu valley is sandwiched between the Pir Panjal, Lower Himalayan and Great Himalayan range.', '24x7 Hrs', '', 'assets/images/manali/kullu/img1.jpg', '', 0),
(4, 'Rohtang Pass', 1, 'Rohtang pass is an adventure tourist site where it can be cold even on a summer day. It is the highest point on the Manali-Keylong road and provides a wide panoramic view of mountains rising far above clouds, which is truly breath taking. Close by is a small lake called Dassaur Lake. Beas Kund, the source of river Beas, is also nearby. In winter, the road of Rothang Pass is closed. If you are an adventure freak, you are in for a pleasant surprise as Rohtang Pass makes for some smashing adrenalin', '24x7 Hrs except Tuesday.', '', 'assets/images/manali/rohtang-pass/img1.jpg', '', 0),
(5, 'Solang Valley', 1, 'Solang Valley gives you stunning views of the snow capped peaks and beautiful glaciers. If you are in an adventurous mood, indulge in some skiing, paragliding or exciting ATB rides. There are a bundle of surprises in store for kids as well.\nIt is also an awesome picnic spot. There are innumerable shops selling delicious snacks.\n', '10:00 AM - 06:00 PM', 'Entry Fees: Rs 500 per person for zorbing \n RS 1,200 per person for paragliding \n Rs 500 per person for ropeway (both side\n', 'assets/images/manali/solang-valley/img1.jpg', '', 0),
(6, 'Van Vihar', 1, 'Away from the hustle bustle of the busy market, this protected piece of land is maintained by government authorities. The vast forest area has a children''s park complete with swings and slides and a small man made pond for boating. the Van Vihar is a perfect place to relax and rejuvenate.\n', '08:00 AM - 07:00 PM\n', 'Entry Fees: 10 Rs Per Person', 'assets/images/manali/van-vihar/img1.jpg', '', 0),
(7, 'Vashishta Hot Springs', 1, 'Soak yourself in Vashist Hot Water Sulphur Springs (across the famous Beas river) and feel the magic. The place has several modern bathrooms with Turkish style showers(connected to the spring through pipes). It is flocked by visitors who want to benefit from the medicinal properties of the sulphur spring as it is said to cure a number of skin allergies and other ailments.', '7:00 AM - 1:00 PM , \n2:00 PM - 10:00 PM\n', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(8, 'Kasol', 1, 'Kasol, like many other Himalayan destinations, haunts you and invites you again and again. The\n\ndense pinewood-covered forests with little villages tucked in cosy corners make the topography all the \n\nmore exciting and is well-complimented by the fierce flow of the Parvati accompanying you from \nBhuntur.', 'Day time', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(9, 'Manikaran', 1, 'Manikaran is located in the Parvati Valley between the rivers Beas and Parvati, northeast of Bhuntar in the Kullu District of Himachal Pradesh. It is at an altitude of 1760 m and is located about 45 km from Kullu.\n\nThis small town attracts tourists visiting Manali and Kullu to its hot springs and pilgrim centres. An experimental geothermal energy plant has also been set up here.', 'Day time', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(10, 'Shiva Mandir', 2, 'Shiv Mandir is hugely revered as it belongs to Lord Shiva. However, an\r\n\r\nin 1905 caused damage to the temple and it was slightly tilted. The importance of Manikaran is also \r\n\r\njudged from the fact that devtas of Kullu valley pay regular visit to this place on specified dates.', '8:00 AM - 8:00 PM\r\n', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(11, 'Sri Ram Mandir', 2, 'Ram Mandir was constructed by Raja Jagat Singh in the 17th century when the idol\r\n\r\nof Lord Rama was brought from Ayodhya.', '7:00 AM - 7:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(13, 'Tibitan Bazar', 2, 'Tibitan bazaar here has been here since years and it still retains its glory.There\r\n\r\nare variety of items available here ranging from winter clothing to tibetan spices.There are many \r\n\r\neateries present nearby.', '7:00 AM - 7:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(14, ' Manikaran Gurudwara', 2, 'Manikaran Gurudwara in the small town of Manikaran is visited by\r\n\r\nall through the year. It is said that the Sikh founder, Guru Nanak Devji visited Manikaran to help the people. \r\n\r\nThe natural hot thermal spring is considered to pe pious and it is said that a dip in the spring will guarantee \r\n\r\none a place in heaven. The gurudwara also has a free food community or langar for one and all. One should \r\n\r\ncertainly have the heavenly langar served here.', '5:00 AM - 12:00 PM\r\n\r\n4:00 PM - 9:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(15, 'kasol', 2, 'Kasol-Kasol, like many other Himalayan destinations, haunts you and invites you again and again. The\r\n\r\ndense pinewood-covered forests with little villages tucked in cosy corners make the topography all the \r\n\r\nmore exciting and is well-complimented by the fierce flow of the Parvati accompanying you from \r\n\r\nBhuntar.', '5:00 AM - 12:00 PM\r\n\r\n4:00 PM - 9:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(16, 'christ church', 3, 'Christ Church of Shimla is a beautiful architectural masterpiece.The church looks absolutely magical \r\n\r\nduring night when lights placed at strategic corners illuminate this beautiful church. The church glows \r\n\r\nwith all its beauty and grandeur and is an amazing sight to look at. Beautifully painted stained glass form \r\n\r\nthe windows of this magnificent church.', '8.00 AM - 6.00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(17, 'jhaku temple', 3, 'Dedicated to Lord Hanuman, this temple is at an altitude of 8048 feet above sea level\r\n\r\nnear the highest point of Shimla ridge. It offers a panoramic view over the surrounding valleys , out to \r\n\r\nthe snowcapped peaks, and over the town itself. Jakhu is a vantage point for witnessing the changing \r\n\r\nskyline as the sun rises or sets.', '5:00 AM - 12:00 PM\r\n\r\n4:00 PM - 9:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(18, 'Shimla Heritage Museum', 3, 'Glance and marvel at the collection of photos and pictures that belonged to\r\n\r\nthe British Raj Era in Shimla at this museum. The Shimla heritage museum is housed in a 120 year old \r\n\r\nheritage building itself, formerly known as the US Club.', '10:00 AM - 05:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(19, 'summer hill', 3, 'A former place of residence of the Great leader Mahatma Gandhi, is a small town in itself\r\n\r\nand is also known as Potter’s Hill. It is a beautiful little village with deep deodar forests .An ideal picnic \r\n\r\nspot or a day-out. It is a delight to the photographers.', '24x7', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(20, 'Tara Devi Temple', 3, 'Located on the Tarav Parvat in Shimla, the temple is dedicated to the Goddess Maa\r\n\r\nTara Devi who is believed to look after the city of Shimla with her protective Gaze. \r\n\r\nDating back to 250 years, the Idol is said to be brought all the way from the eastern state of Bengal, and \r\n\r\nis made of 8 different metals, making it even more auspicious.', '07:00 AM - 06:30 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(21, 'himalaya nature park', 3, 'park:Situated about 18 km from Shimla, at over 2,600 metres altitude, the Himalayan\r\n\r\nNature Park is located amidst 90 hectares of temperate vegetation that forms natural habitat for many a \r\n\r\nwild animals of the Western Himalaya.', '10:00 AM - 05:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(22, 'The ridge of shimla', 3, 'a large open spacious platform from where you can have a panoramic view of\r\n\r\nthe mountain peaks of Shimla. The snow capped mountain ranges engulfed in the beauty of the nature \r\n\r\nis a phenomenal view that the Ridge of Shimla offers to the crowd.', '08:00 AM - 06:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(23, 'Anandale', 3, 'Gigantic cedars welcome as one gets into the environ of the winding woods. Nestled in the\r\n\r\nfoot of the hills, the Army Heritage Museum at the Annandale is an unsung jewel. Very different from \r\n\r\nthe chaos, the hustle and the bustle of the Mall- it serves literally as a mind-refresher. Secluded and \r\n\r\nserene- here the air tastes chilled cocktail, the exquisite vegetation serving as the ingredients.this \r\n\r\nMuseum describes the best of the Indian Army. This museum however, has a unique style o', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(24, 'Kufri Fun World', 3, 'Kufri Fun World is located at the top of Mahasu peak. At over 2,800 metres\r\n\r\nabove sea level, it is one of the highest amusement parks in the world and is famous for having \r\n\r\nthe highest go-kart track on the planet. Getting to the park is an adventure in itself. At Kufri Fun \r\n\r\nWorld enjoy the thrill of riding the swinging boat and the merry-go-round at the top of a \r\n\r\nmountain, all to the backdrop of the latest popular local tunes.\r\n\r\n\r\n\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(25, 'iias also known as viceregal lodge or rashtrapati niwas-', 3, 'This building constructed in Scottish architectural type is an awesome one. The building , gardens are \r\n\r\ntreat to watch. u may be amazed at its beauty. you are shown 3 rooms inside involving photos , furnitures  \r\n\r\netc which have become part of history.', '10:00 AM - 05:00 PM', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(26, 'The Mahakal temple', 4, 'The Mahakal temple atop the Observatory Hill is a most revered place for the locals and you will\r\n\r\nbe surprised to find a Hindu priest sharing a common altar with a Buddhist monk. Prayers are \r\n\r\nchanted by a hindu priest while a Buddhist monk reads from the Buddhist Holy Scriptures. Devotees \r\n\r\ncircumambulate the shrine three times, barefoot while ringing the bells that are placed around it. You \r\n\r\nwill see hundreds of prayer flags hung all over the shrine and on trees, fluttering in the bre', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(27, 'Happy Valley Tea Estate', 4, 'Happy Valley Tea Estate is located at the end of the T. P. Banerjee Road, in the vicinity of\r\n\r\nDarjeeling town, about 15 minutes walking distance, which is between 2 to 3 kilometers from the town. \r\n\r\nIt is one of the major tourist attractions for its beautiful carpeted greenery which may sweep scenery \r\n\r\nlovers off their feet as they may get a bird’s eye view from the Hill Cart road. It also has a museum and \r\n\r\nhas a factory which is the highest in the world.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(28, 'Darjeeling Passenger ropeway', 4, 'Darjeeling Passenger ropeway-The ropeway is a popular tourist destination in the town. It consists\r\n\r\nof sixteen cars and plied between the "North Point" in the town of Darjeeling and Singla on the banks \r\n\r\nof the Ramman river. From the cable car you can get breathtaking view of the valley \r\n\r\nbelow, see the spread of lush green tea gardens on the hill slopes, flowing rivers, \r\n\r\nforests, waterfalls and to top it all the magnificent view of the Eastern Himalayan \r\n\r\nrange including the snow cap', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(29, 'Padmaja Naidu Himalayan Zoological Park ', 4, 'Padmaja Naidu Himalayan Zoological Park in Darjeeling was established on the 14th of\r\n\r\n1958, in the fond memory of Padmaja Naidu, the former Governor of West Bengal. It is one of the best zoos \r\n\r\nin the country and is known internationally for its breeding programmes of the snow leopard and the red \r\n\r\npanda. You will also see Siberian tigers and Tibetan wolves here. Breeding programmes for the endangered \r\n\r\nanimals like the Red Panda, Snow Leopard and the Siberian Tiger are also carried out ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(30, 'Himalayan Mountaineering institute', 4, 'Himalayan Mountaineering institute- This Institute was founded and managed by the late Tenzing Norgay\r\n\r\nwho conquered Mt Everest with Sir Edmund Hillary in 1953. Today, it has on display records of some major \r\n\r\nexpeditions undertaken. Next to this is the Everest Museum, which traces the history of different attempts on \r\n\r\nthe world''s highest peak. Aone-off rock-climbing session can be taken at the Tenzing Norgay Rock, located on \r\n\r\nthe northern fringes of Darjeeling.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(31, 'Tiger Hill', 4, 'Tiger Hill is a famous railway station in Darjeeling and the highest one in the country.  It is situated\r\n\r\nalmost 11 kms away from Darjeeling and buses, autos, and other transport facilities are available to \r\n\r\nreach there easily. The real attraction of Tiger Hill is the spectacular vantage point it provides. One \r\n\r\ncan easily view the world’s highest peak, Mount Everest from the Tiger Hill.  It is referred to as one \r\n\r\nof the World Heritage Sites by UNESCO, considering its huge economical a', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(32, 'Ghoom Monastery', 4, 'Ghoom Monastery is located about 800 ft above the sea level at Ghoom. The monastery is also a\r\n\r\nstorehouse of Tibetan translations of famous Sanskrit works, such as the Meghdoot by Kalidasa, \r\n\r\nNagamandala by Sriharsa and Nyaya Krit by Dharmakriti, to name a few. Visit the Ghoom monastery, not \r\n\r\njust to experience the spirituality of the place but also the breathtaking beauty of the surroundings.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(33, 'Batasia Loop', 4, 'Located on a hill top, this is a garden like place through which the toy train passes in a loop-\r\n\r\nlike pattern. This scenic place also has a Gorkha martyr memorial.  There is a small market near the loop \r\n\r\nas well. The loop along with its surrounding is so beautiful that the passerby is inclined to take \r\n\r\npictures so be sure to keep your cameras handy.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(34, 'The Rock Garden', 4, 'The Rock Garden, also known as Barboety Rock Garden is located some 10 km away from\r\n\r\nThis place is thriving as popular and attractive scenic spots around Darjeeling city. Cascading waterfalls \r\n\r\namidst the natural splendor makes it a sought after place among tourists. One can enjoy boating here and \r\n\r\nindulge in some of the local delicacies.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(35, 'Japanese Peace Pagoda.', 4, 'The Japanese Peace Pagoda, also known as the Nipponzan\r\n\r\nMyohoji Buddhist Temple, is famous for its tranquil atmosphere and the serenity. It is a \r\n\r\nrevered place that is believed to be a symbol of spirituality and peace. Nestled in the vicinity to the pagoda \r\n\r\nare a Buddhist temple and a monastery, built in traditional Japanese style.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(36, 'The Lloyd''s Botanical Garden', 4, 'The Lloyd''s Botanical Garden represents the best combination of flora and fauna in Darjeeling. It\r\n\r\nwas built in the year 1878, it has an area more than 40 acres. It is for the most part quite similar to \r\n\r\nthat of the Calcutta Botanical garden. It has several species of bamboo, oak, magnolia, wild \r\n\r\ngeranium and so on. The collection of native orchids is a special attraction in this garden. The \r\n\r\nGarden is situated at an elevation of about 6,000 ft. With an average annual rainfall of almo', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(38, 'Toy train joy rides', 4, 'Toy train joy rides operate from Darjeeling Railway Station. It''s a 2-hour round\r\n\r\ntrip from Darjeeling up to Ghum and back covering a total distance of 14kms. There \r\n\r\nare four such round trips in a day, two in the morning half and two in the \r\n\r\nafternoon.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(39, 'Kufri', 3, 'Kufri, a tiny charming hill station at the foothills of the great Himalayas, is situated at the\r\n\r\nsouthern part of the state of Himachal Pradesh and is popular for its pleasant climate and \r\n\r\npicturesque beauty. Famous spots to visit in and around Kufri are The Himalayan Nature Park and \r\n\r\nIndira Tourist Park. Tourists can enjoy the grand panoramic sights of the green valley and the snow \r\n\r\nclad foothills of Himalayas. A horseback ride to discover the overwhelming hilly regions is an \r\n\r\nexp', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(40, 'Chail', 3, 'Home to the world''s highest cricket and polo ground, this picture-perfect hillstation is an amazing\r\n\r\nretreat destination. Away from the maddening crowds of the city, this piece of paradise is in close proximity \r\n\r\nto the more popular Shimla. The city boasts a royal legacy, visible in its few but grand buildings. \r\n\r\nChail offers a kaleidoscope of great views, especially of the Sutlej Valley, amidst the graceful pine and \r\n\r\ndeodar forests.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(41, 'The Tashi', 5, 'The Tashi viewpoint is an interesting way to avail panoramic views of the city of Gangtok right up\r\n\r\nto the Nathula. Seeing the Kanchenjunga from here is sure to be a lovely experience. You can also \r\n\r\nenjoy unmatched views of Labrang Monastery and Phodong Monastery, which are situated on the opposite \r\n\r\nhills. The area around it being quite picturesque, the place is a great picnic spot for families. The \r\n\r\nfresh and yummy food at the local kiosks is another added plus.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(42, 'The Himalayan Zoological Park ', 5, 'The Himalayan Zoological Park or the Gangtok Zoo is sure to be one of the most unique zoo\r\n\r\nexperiences. All of nature’s bounty that the Himalayas have been blessed with has been preserved \r\n\r\nhere in a rare collection. The Red Panda, the Snow Leopard and many other lovely and unique \r\n\r\nHimalayan creatures can be seen here, in a largely preserved habitat. The species you will see are \r\n\r\nsimply astonishing. The clouded leopard, leopard cat etc. are some other animals that shouldn’t be \r\n\r\nmiss', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(43, 'Ganesh Tok', 5, 'The beautiful hillock Ganesh Tok calls for a wonderful weekend getaway while you are in\r\n\r\nGangtok. You would be mesmerised by the scenic beauty that envelops this place. Situated at a height of \r\n\r\n6,500 m, there is a small temple dedicated to Lord Ganesha, however, the temple is so small that it can \r\n\r\naccommodate only one person at a time.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(44, 'Hanuman Tok,', 5, 'Hanuman Tok, which is similar to the Ganesh Tok is another very interesting Hindu religious site\r\n\r\nin Gangtok. There is a Hanuman Temple in the region which is considered to be sacred. Hindus \r\n\r\nfrom all over the country visit this place precisely for its religious significance. But if you are not \r\n\r\nreligious it is no matter. The Hanuman Tok also happens to be one of the two best viewpoints in the \r\n\r\ncity as well. The surroundings of the temple are as beautiful as the temple itself and the ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(45, 'Tsongmo Lake', 5, 'Tsongmo Lake is most definitely a must visit summer as well as winter site near Gangtok. About\r\n\r\n2 hours from the city this serene glacial lake is a lovely retreat for the Sikkim tourist. Many flowering \r\n\r\nplants like Primula and other flora like Alpine trees add an element of surreal beauty to the lake. You can \r\n\r\nalso experience a Yak ride for approx INR 650 per person around the lake. Since it is a part of the restricted \r\n\r\narea, prior permission from the tourism department is mandatory. ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(46, 'Nathu La', 5, 'Nathu La is a definite must visit from the city of Gangtok. This Pass in the Himalayas is on the\r\n\r\nborder between India and China and one of the most interesting sites to see in Sikkim. The pass, at \r\n\r\n4,310 m (14,140 ft) above mean sea level has very low temperatures, so make sure you carry heavy \r\n\r\nwoollens when you visit here.', 'NATHU LA is open from Wednesday to sunday.', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(47, 'Baba Mandir', 5, 'It is said that Baba Harbhajan has been guarding the international boundary of the two\r\n\r\nAsian giants, the China and India over the last three decades. Over the years the shrine of Baba \r\n\r\nHarbhajan has obtain huge devote across all frontiers. Baba is respected and worshiped by every army \r\n\r\nmen in', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(48, 'Do Drul Chorten Stupa', 5, 'One of the many Buddhist sites in Gangtok, the Do Drulchortena Stupa is\r\n\r\none of the most important ones and certainly a must visit site in the city. The Stupa is very popular \r\n\r\nand highly recommended by tourists. You will be able to see several religious texts from the Tibetan \r\n\r\nsect of Buddhism in this place that is considered to be holy.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(49, 'Namgyal Institute of Tibetology', 5, 'Housing a range of Buddhist manuscripts and books, stunning\r\n\r\ncloth paintings depicting Tibetan art, sacred objects and statuettes among others, the Namgyal \r\n\r\nInstitute of Tibetology is a must visit for people who want to know more about the Tibetan culture \r\n\r\nthat is an inherent part of this region.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(50, 'The ridge Park', 5, 'The ridge Park or simply the Ridge is an interesting tourist destination within Gangtok. Not far\r\n\r\nfrom the local market, it is a refreshing stop for the weary tourist or the tired shopper. It might be \r\n\r\njust a small stretch of green meadow in the city but its location makes it quite popular with the \r\n\r\ntourists as well as locals. There are a couple of statues and other sculptures worth seeing in and \r\n\r\naround it.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(51, 'Dainkund peak', 6, 'The Dainkund Mountain is located in Dalhousie in the district of Chamba. The\r\n\r\nDainkund peak is at a height of almost 2755 meters above sea level.The name Dainkund is said to have \r\n\r\nbeen derived from ‘Dain – Kund’, which means ‘house of the witches’\r\n\r\nACTIVITIES:The peak is a steep climb of 250 odd steps. The main access is with the help of trekking', '24x7', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(52, 'St. John''s church', 6, 'The oldest church in Dalhousie and an important tourist place in Dalhousie, the\r\n\r\nSt.John’s church is set in a beautiful backdrop and is quite a sight to behold. Housed in a British-era \r\n\r\nbuilding, this Protestant church is one of the most visited churches in town.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(53, 'Ganji Pahari', 6, 'GanjiPahari is a small hill located just a little far from the city of Dalhousie. It is a lovely\r\n\r\nwalk just a few kilometers from the Bakrota hills. The name ‘GanjiPahari’ literally means ‘bald hill’. It is \r\n\r\nso called because the hill is completely devoid of all vegetation.There is also a beautiful Kali Temple on \r\n\r\nthe peak of the GanjiPahari.\r\n\r\nACTIVITIES:The only way to reach the peak is by trekking.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(54, 'Gandhi Chowk', 6, 'Gandhi Chowk is the most happening shopping area in Dalhousie with a number of\r\n\r\nshops and delectable eateries scattered all over the place. It is the central area of Dalhousie, with the \r\n\r\nmost important buildings, post office and restaurants along with a small Tibetan market selling \r\n\r\nhandicrafts items situated in the vicinity.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(56, 'Rang Mahal', 6, 'Rang Mahal exhibits a fusion of Mughal and British architecture. It has an interesting\r\n\r\ncollection of paintings and the architecture of the building is quite unique. A one of a kind tourist spot in \r\n\r\nDalhousie, the Rang Mahal looks like a place fit for royals. It is opulent and larger than life.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(57, 'Satdhara falls', 6, 'Known to have magical therapeutic powers, the brooks of Satdhara falls are not only\r\n\r\nbeautiful but also carry legends of the past. This scenic spot is ideal to spend the better part of the day \r\n\r\nand is a must visit in your Dalhousie travel itinerary.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(58, 'Panchpula', 6, 'Panchpula is located at a distance of around 3 km from Dalhousie. One of the famous\r\n\r\npicturesque spots in the region, the word Panchpula means five bridges. It is the place where a \r\n\r\ndescending stream pours into and feeds several pools. The stream originates from the northern side \r\n\r\nof Dayakund, which then cuts through a ravine to fall into the water bodies located in Panchpula.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(59, 'Upper Bakrota', 6, 'The upper Bakrota is the highest point in Dalhousie. It has a number of\r\n\r\npicturesque estates, a residential and army barracks. The area is surrounded by a loop walk called \r\n\r\nthe Bakrota Walk. This pathway offers a stunning view of the surrounding valleys. The must visit \r\n\r\nhere is the Snowdown Residence. It is said that here Rabindranath Tagore got inspired to later make \r\n\r\nShantiniketan.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(60, 'Kalatop Khajjiar Sanctuary', 6, 'Kalatop Khajjiar Sanctuary is an animal sanctuary at\r\n\r\ndistrict of Himachal Pradesh, India. The sanctuary area is well laid out for trekking trails both at \r\n\r\nKalatop and Khajjiar. There is a dense deodar and fir forest covering 19.63 km² of the \r\n\r\nsanctuary. Pheasants, serow and black bear are some of the common animals found here.[1] The \r\n\r\nsanctuary lies in the path of the Ravi River, and is surrounded by coniferous', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(61, 'Khajjiar Lake', 6, 'Khajjiar lake is situated in Khajjiar, in Chamba district of\r\n\r\nIt is situated at a height of around 1,920 m above sea level between Dalhousie and Chamba Town. \r\n\r\nThe lake is set in a huge grassy landscape, with evergreen cedar trees surrounding it from all sides. \r\n\r\nThe lake takes its name from Khajji Nag. The lake has considerably shrunk over the years and is \r\n\r\nnow almost on the verge of vanishing.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(62, 'Khajji Naag temple', 6, 'Situated close to the lake is the Khajji Nag Temple that dates back to the 12th\r\n\r\ncentury AD, and is considered one of the holiest and ancient temples in Himachal Pradesh. This \r\n\r\ntemple is dedicated to Khajji Nag, who is the Lord of the Serpents. The construction of this temple \r\n\r\nbegan in the 10th century AD and is reflected in the architecture of the temple that exhibits a mix of \r\n\r\nHindu and Muslim style.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(63, 'Panch Pandav tree', 6, 'The Panch Pandav Tree is situated in the ground of Khajjiar. The tree is\r\n\r\nfamous for its shoots. Although the main root of the tree and the shoots are same, there are six \r\n\r\nshoots branching out from the tree.\r\n\r\nAccording to the local inhabitants, the five shoots of this tree stand for the Five Pandavas and the \r\n\r\nlast one symbolises Draupadi. This tree is close to a rest house that leads the way to Khajjiar School \r\n\r\nand a small village.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(64, 'Dirang valley', 7, 'Dirang Valley is a stunningly picturesque valley that lies between Bomdila\r\n\r\nand Tawang.Dirang, the town situated in the valley has a pleasant weather that makes for \r\n\r\na comfortable stay. The views from Dirang are mind blowing. If you love trekking, you \r\n\r\nwould the high peaks in Dirang irresistible. Dirang is also famous for hot water \r\n\r\nspringsand apple orchards that enhance the natural beauty of the place.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(65, 'The Sela pass', 7, 'The Sela Pass (more appropriately called Se La, as La means Pass)\r\n\r\npass located in Tawang District of Arunachal Pradesh state of India.  The pass has hardly any \r\n\r\nvegetation and is usually snow-covered to some extent all through the year. During winter \r\n\r\ntemperature in the pass can go down to ?10 degrees.You may stop here to enjoy the scenic \r\n\r\nbeauty and also to click some pics!', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(66, 'Madhuri Lake', 7, 'Madhuri Lake situated at 12000 ft above sea level was formed as a result of an earthquake, this\r\n\r\nwater body is crystal clear and reflects the color of the blue sky. Numerous dead tree trunks, which \r\n\r\nonce were alive (before the earthquake) emerges from the blue water of the lake creating a strange \r\n\r\nyet beautiful imagery before visitors. One can stroll around the lake with their families and enjoy the \r\n\r\nnatural beauty of the place.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(67, 'Bumla Pass', 7, 'Bumla Pass is located 37 kms away from Tawang. It is one of the most off-beat passes in the world\r\n\r\nand is also known as the pass from where Dalai Lama entered India escaping from Tibet. \r\n\r\nThe road to Bum-la is also historical route in the sense that it is from here that the Chinese marched into \r\n\r\nIndia during the 1962 Sino-Indian war.\r\n\r\nNOTE: A special permit is required to visit Bum La Pass.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(68, 'Tawang Monastery.', 7, 'The largest monastery in India and the one of the largest of the Mahayana\r\n\r\nmonasteries in Asia, Tawang Monastery is a must-visit place for any tourist visiting the state of Arunachal \r\n\r\nPradesh. Standing tall at a height of 3300 metres above sea-level, this monastery is a sight that will be \r\n\r\netched forever in your memory.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(69, 'Tawang War Memorial', 7, 'Tawang War Memorial, a 40 foot high multi-hued memorial, has a structure constructed in stupa\r\n\r\ndesign. Dedicated to the martyrs of Sino-India War held in 1962, this memorial is nestled among \r\n\r\nbeautiful peaks, which overlooks the Tawang-Chu valley. Popularly known as Namgyal Chorten, the \r\n\r\nmemorial has names of 2,420 dead soldiers. The names of the soldiers are etched in gold on around \r\n\r\n32 black granite plagues.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(70, 'Nuranang waterfalls', 7, 'Nuranang waterfalls lies in between Tawang and Bomdila road. This waterfall is magnificent and\r\n\r\nis about 100m high. This waterfall is also known as Jang Waterfalls as it is located in a place named \r\n\r\nJang. One can have a very close view of this waterfall as it is too close from the viewpoint', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(71, 'Ward''s lake', 8, 'Ward''s Lake. Located in the heart of the city, this horse-shoe shaped lake is a popular spot\r\n\r\nto take a lazy walk or admire the green lawn dotted with multi-coloured flowers. \r\n\r\nThere is also a Botanical Garden near the lake which has various orchids, apart from the several other \r\n\r\nvarieties of flora that adorn it. The bridge in the midst of the lake is the perfect place to enjoy a view of the \r\n\r\nwhole lake, and maybe even feed the fish! \r\n\r\nENTRY FEE\r\n\r\n Rs 5 per person for entry \r\n\r\n Rs ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(72, 'Shillong Baptist Church', 8, 'A towering building in the city of Shillong, the Shillong Baptist church is one\r\n\r\nof the most popular churches in the state. A favourite spot for Christian wedding celebrations in the town, \r\n\r\nthis church always seems to be flocked by people, who come here for one event or the other. Experience \r\n\r\npeace and serenity as you pray at the altar of this holy church and instantly feel closer to the divine forces.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(73, 'Shillong Peak', 8, 'Shillong Peak is the highest peak of the province of Himalayas, standing at an\r\n\r\naltitude of 1,965 metre above the sea level. One of the most visited sites of the hill station, this peak \r\n\r\nprovides a breathtaking view of Shillong city and Himalayan ranges. The star-studded night along \r\n\r\nwith the city lights is a treat to witness.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(74, 'Elephant falls', 8, 'Elephant Falls are perhaps the most popular tourist destination in Shillong. The first\r\n\r\nthat you will witness after reaching the spot is the foaming white water, gurgling down the stony steps. This \r\n\r\ncrystal clear water is in contrast with the greenery on the sides of the waterfall, adding to the beauty of the \r\n\r\nplace. The waterfall is believed to have gotten its name from a huge elephant-shaped rock near it.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(75, 'Golf course', 8, 'Golf Course of Shillong, is one of the oldest golf courses in the country,\r\n\r\ncommissioned during British regime.It stands amidst pine groves and rhododendron trees at an \r\n\r\naltitude of 5,200 ft. above sea level. The golf course in Shillong is one of the largest and natural golf \r\n\r\ncourses in Asia. It is considered to the wettest golf courses in the globe. The scenic beauty all \r\n\r\naround is superb and a must visit destination for all.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(76, 'Laitlum Canyons', 8, 'Laitlum Canyons is one of those spots where you can have a bird''s eye view of the\n\nof Shillong. The green hills, the orchids, the bamboo plants, the ''cottony'' clouds - all from one point. \n\nAmazing, isn''t it? For the trek uphill, make sure you are wearing your most comfortable shoes. I''ts a long \n\nwalk to the top, but with the variety of floraaround you for company, you wouldn''t care much about those \n\ntired muscles. Yes, you can try it, after all, the literal meaning of ''Meghalaya'' is ''''The Abo', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(77, 'David Scott Trail', 8, '- The trek takes you across the beautiful terrain of East Khasi Hills and\r\n\r\naround 16 km. During this four hour walk you will cross streams, dodge waterfalls, trudge through \r\n\r\nmeadows, pass through sacred groves, valleys and Khasi villages. Be sure to be immersed in the \r\n\r\nnature and the beauty it offers, there are amazing rock formations across the trek and you are sure \r\n\r\nto wonder and thrilled about them.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(78, 'Umiam lake', 8, 'Umiam Lake is a beautiful lake that sees numerous tourists from all over the country.\r\n\r\nscenic spot is a part of a hydro-electric project, Umiam Umtru Hydro Electric Power Project, which resulted \r\n\r\nin the construction of this lake. Also known as Big Water or Barapani, this lake is an ideal place to \r\n\r\nexperience the natural splendour of Shillong. The surrounding emerald-coloured hill is another add-on to the \r\n\r\nbeauty of this place.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(79, 'Spread eagle falls', 8, 'Cutting through rocky terrains, meandering amidst the green forests of\r\n\r\nMeghalaya, Spread Eagle Falls or Urkaliar, spreads its water over a wide region, making it one of the most \r\n\r\nwidest waterfall in the region. Surrounded by steep, beautiful hills, this waterfall is a sight that will be \r\n\r\nengraved in the hearts of all tourist, who come here to enjoy its mesmerising views. Since the spot is \r\n\r\nsituated in the forested region of the state, it is serene and peaceful, making it a favourite ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(80, 'Shillong catholic cathedral', 8, 'Built on the same spot, which witnessed the first church in Shillong, this\r\n\r\nhistorical monument of peace and divinity is almost 50 years old. The beautiful church is constructed in the \r\n\r\nGothic architectural style and is a spectacular sight in the midst of sprawling green lawns. This church is also \r\n\r\nknown as the Cathedral of Mary Help of Christians. The most unique feature of this church is the fact that it \r\n\r\nis built on sand and not on rock.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(81, 'Don Bosco Centre for Indigenous Cultures', 8, 'Don Bosco Centre for Indigenous Cultures is a famous museum that is known for preserving\r\n\r\nculture of the various tribes and communities of Northeast India. This place is run by the Salesian order of \r\n\r\nthe Catholic Church and has a gigantic archive of information on the states of Assam, Meghalaya, Manipur, \r\n\r\nMizoram, Nagaland, Arunachal Pradesh and Tripura.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(82, 'Mawlynnong Village', 8, 'A serene hamlet in the state of Meghalaya, Mawlynnong Village\r\n\r\nby emerald-green trees and a variety of flora, all adding to the beauty of this place. With the reputation of \r\n\r\nbeing one of the cleanliest villages in Asia, this picturesque village is a change from the busy and congested \r\n\r\ncity-scape. With colourful orchids flowering amidst the green leaves of trees, you will be greeted with the \r\n\r\nmost beautiful enchanting sight of nature. Apart from this, the dedication of the villagers to', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(83, 'Living Root Bridges', 8, 'Living Root Bridges are built especially using the secondary root systems that grow higher up on\r\n\r\ntrunk. To prevent these roots from flaring out on all directions and guiding them the right way, hollowed out \r\n\r\nbetel nut trunks are used. Once the roots extend over to the other side of the river, they are allowed to take \r\n\r\nroot. A good sturdy bridge may take anywhere from 10 to 15 years to be completely built and can easily \r\n\r\ncarry the weight of more than 50 people.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(84, 'Mawsynram', 8, 'Mawsynram, a small village, is located at a distance of approximately 15 km from\r\n\r\nCherrapunjee. The village is visited by large number of tourists owing to the Mawjymbuin Cave, \r\n\r\nwhich is several years old. Famous for stalagmite whose shape is similar to that of Shiva lingam, the \r\n\r\ncave is visited large number of devotees every year. The annual rainfall in this region is about \r\n\r\n11,872 mm, which gives a close competition to Cherrapunjee.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(85, 'Nohkalikai waterfalls', 8, 'Nohkalikai Waterfalls, located at a distance of 5 km from Cherrapunjee, is\r\n\r\nthe fourth highest waterfall in the world. . A viewing gallery allows the visitor to take in the vista which \r\n\r\nis, often, at the mercy of the mist that sweeps in frequently. A flight of stairs also takes tourists down \r\n\r\nto more viewing points.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(86, 'Eco Park', 8, 'Thangkharang Park(Eco park) is situated 12 km from Cherrapunjee. A small one way road slithers down a gentle slope, covered with trees. The best thing about the park is that it gives panoramic view of the plains of Bangladesh. Inside the park, visitors can see the Khoh Ramhah rock, which in its shape is like an upside down basket. It also overlooks the massive Kynrem falls, cascading down in three steps. The view from here is extraordinary and there is nothing to block it except for fog during t', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(87, 'Seven sisters falls', 8, 'Known for being one of the tallest waterfalls in North East India, the Seven Sisters Falls or the Nohsngithiang Falls consists of seven different streams, one of them falling from a height of 250 m. You must visit these falls to witness how the seven sisters dance playfully down the mountains and make up for an interesting touristy for nature lovers.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(88, 'Double Decker Living Root Bridge', 8, 'Double Decker Living Root Bridge, a root bridge, is located in Tyrna village. Made using Indian Rubber Tree, also known as Ficus Elastica, this bridge is one of the popular attractions of the place. In addition, it is also considered as one of the unique examples of bioengineering. The two–tier bridge is more than 100 ft long, which have a carrying capacity of around 50 people at a time. Having Umshiang River flowing beneath the living root bridges, it has been estimated that these are around 50', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(89, 'Kajiranga National Park', 9, 'Sheltering a major portion of world''s population of Rhinos, Kaziranga is one among the five natural UNESCO world heritage sites in India. It is home to the Great Indian One Horned Rhinos and many other exotic species that makes this National Park one of the most sought after destinations for the wildlife buffs.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(90, 'Brahmaputra river ', 9, 'Brahmaputra river side has a spectacular view. In the month of April a vibrant beach festival takes place here. On other days you can just choose to spend hours enjoying the cool breeze on the river banks or take a serene boat/ferry ride in the vast river and catch a sight of the river dolphins playing in the water.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(91, ' The Kamakhya Temple', 9, ' The Kamakhya Temple in Guwahati is one of the most famous and ancient temples in India. Perched on Nilachal Hill about 8 km west of the city, Kamakhya temple is a compulsory stop for the pilgrims on “Tirth Yatra”. The temple is dedicated to the Mother Goddess Kamakhya who is believed to be the essence of female energy. It is one among the 108 Shakti Peethas of Goddess Durga.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(92, 'Assam State Zoo', 9, ' Assam State Zoo and the Botanical Gardens housed within the zoo. The  exquisitely landscaped Gardens was established in 1982. A home to diverse species of herbs, palms, shrubs and conifers, it spreads over an area of 85 hectares. \r\n\r\nOne of the main attraction of this place is the Orchid house which boasts of a collection of more than 40 varieties of rare orchids gathered from the entire North East region of the country. The gardens are open on all days except Fridays.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(93, 'Hayagriba Madhaba temple', 9, ' Right on the northern banks of the Brahmaputra, Hajo is an ancient pilgrim spot of three religions - Hindu, Islam and Buddhism. The most famous attraction happens to be the Hayagriba Madhaba Temple, which is frequented by both Hindus and Buddhists. Some believe that Buddha attained Nirvana in this place, hence the temple is frequented by both Buddhist lamas and Bhutiyas, especially during the winter season. \r\n\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(94, 'The Nehru Park', 9, ' The Nehru Park, situated right opposite the famous Cotton College in Guwahati, is a very popular tourist attraction in the city. Named after the first prime minister of India Jawaharlal Nehru, this beautiful park is open for all. The area where the park is located is an age old institutional area of the city with a number of reputed colleges located nearby.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(95, 'Pobitora Wildlife Sanctuary', 9, ' Pobitora Wildlife Sanctuary is a small reserve of 38 square kilometers, with a large habitation of the famous Great Indian One Horned Rhino. According to the estimation made in 2006 there are more than 80 Rhinos in the forest, which is considerably a pretty high density. You can spot atleast 5 Rhinos in one Elephant safari. The wildlife sanctuary has played a strong role in the conservation of this majestic species, that is regarded as the ''Pride of Assam''.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(96, ' Hawa Mahal', 10, 'Built in 1799 by Maharaja Sawai Singh as a part of the City Palace, Hawa Mahal was an extension of the women''s chamber with the purpose of allowing royal ladies to observe everyday life in the street below without being seen. A five-storey high red sandstone structure complete with over 950 windows, Hawa Mahal was made in such a way that the breeze circulates through these windows, giving the palace its name.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(97, 'Jantar Mantar', 10, 'Lauded as a UNESCO World Heritage Site and located very close to the City Palace, Jantar Mantar is the largest of five astronomical observatories built by Maharaja Jai Singh during the period 1727-1734. Consisting of fourteen major geometric devices for measuring time, predicting eclipses, tracking stars in their orbits, ascertaining the declination of planets and determining the celestial altitudes, the observatory is a major attraction for kids and adults.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(98, 'City Palace', 10, 'Located inside the old city, City Palace is a blend of traditional Rajput and Mughal architecture bound to leave you awestruck. A vast palace complex that occupies nearly a seventh of the Pink City, this palace was originally built by Maharaja Jai Singh II in 1932. Today, City Palace is known for housing the Chandra Mahal and the Mubarak Mahal, apart from the series of courtyards, sprawling gardens and buildings that populate the complex. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(99, 'Govind Dev Ji temple', 10, ' Govind Dev Ji Temple is considered to be the home of city’s ancient divinity, Lord Krishna. If you are a true ''bhakt'', you must not miss visiting this holy temple to acquire his blessings. \r\n\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(100, 'Nahargarh fort', 10, 'Giving brilliant views of the Man Sagar lake and the vast sprawling city of Jaipur, you must see the beautiful Nahargarh Fort that also houses the compact Madhavendra Bhawan palace. It came into popularity even more when portions of the movie Rang De Basanti were shot at this fort.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(101, ' Amer/Amber fort', 10, 'A fort-palace complex built in hybrid Hindu-Muslim style that dates back to the 17th Century, Amber Fort is going to leave you spellbound. Overlooking the Maota lake, this attraction on the outskirts of the city is known for its imposing gateways and cobbled pathways. This magnificent structure was built more than 4 centuries ago by Raja Man Singh I and still retains all its stately grandeur.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0);
INSERT INTO `attractions` (`id`, `attraction_name`, `places_id`, `attraction_about`, `attraction_timeSpan`, `attraction_cost`, `attraction_image`, `attraction_postalCode`, `attraction_overall_rating`) VALUES
(102, 'Jaigarh fort', 10, 'Often called the best fort in all of Jaipur, the Jaigarh Fort features amongst the most well preserved monuments of medieval India. Jaipur was a major region of weapon production during the Mughal times and you can see the specimens of this artillery when you visit the museum inside the fort. This fort was constructed by Maharaja Jai Singh II to protect the Amer Fort in the occurence of an invasion.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(103, 'Jal Mahal', 10, 'Standing tall in the middle of the Man-Sarovar lake in Jaipur, Jal Mahal is a beautiful structure that was built in the 18th century. Reflecting a ''Rajputana'' style, it was constructed by Maharaja Jai Singh II of Amber. It''s interesting to note that you can take a boat ride to this Mahal, sitting elegantly in the handcrafted wooden boats. These boats have been nicely done by the skilled boat makers of Vrindavan. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(104, ' Rambagh Golf Club', 10, ' Rambagh Golf Club is one of the oldest and most prestigious of Golf Clubs in India which is affiliated to the Indian Golf Union. The Golf Course is playable all round the year. The Course is strategically designed on a sandy loam soil and picturesquely located with a nice scenic beauty. Moving around the Course, one is afforded with a view of the Rambagh Palace Hotel, Moti Doongri Fort, Nahargarh Fort and the Birla Planetarium.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(105, 'Central Park', 10, 'Central Park, constructed by the Jaipur Development Authority is the largest park in Jaipur. Having a big lush green beautiful garden and Rambagh Polo Ground and golf club nearby makes it a perfect enjoyable place in Jaipur. Central Park Garden also has a long 5 km jogging and walking track which is the best place for many Jaipurites for walking and jogging. Central Park is also a bird watchers paradise as a number of migratory and native birds visit it round the year. Musical fountain, temple a', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(106, 'Amar Jawan Jyoti', 10, 'Amar Jawan Jyoti was constructed to honor the soldiers and martyrs of Jaipur for their bravery. This place is usually flocked by locals and tourists, as this structure is beautifully lit up during the evening, showcasing a brilliant transformation of one vivid colour into another. It looks beautiful, specially when you are viewing it from Vidhan Sabha.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(107, ' Sawai Mansingh Stadium', 10, 'Sawai Mansingh Stadium, located near Rambagh Circle in Jaipur, is a cricket stadium built during the reign of Maharaja Sawai Man Singh II. The stadium has the the capacity of 30,000 people. In 2006, the stadium underwent a major renovation facilitating it with media rooms, galleries and two new blocks. Today, it is home to the IPL team Rajasthan RoyalsIt has also hosted two World Cup matches in 1987 and 1996. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(108, ' Ramniwas garden', 10, 'Ramniwas garden. Built by Raja Sawai Ram Singh in 1868, the Ram Niwas Garden is spread over an area of 33 acres. The garden houses the Albert Hall Museum (Central Museum). Apart from this museum, you will find a bird park, a zoo, the Ravindra Rang Manch Theatre, exhibition ground, art gallery, gymnasium and several cafes and picnic spots within the garden.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(109, ' Albert Hall Museum', 10, 'Albert Hall Museum, also known as the Government Central Museum, this one of the oldest museums of Jaipur and retains the essence of the Maharajas of Jaipur. The museum houses a number of courtyards, archways and towers standing as a symbol for rich architectural heritage of the country. The Museum displays several miniature paintings along with portraits of the royal kings displayed on the first floor of the museum. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(110, ' Jaipur zoo', 10, 'Spot over 70 varieties of birds, reptiles and mammals when you visit the Jaipur Zoo! Set in the lush green Ram Niwas Gardens, the Zoo is a complete treat for kids and adults alike.\r\n\r\nApart from Sambar deer and Spotted deer, you can also see lions, tigers, panthers and leopards in the zoo! The zoo also has a separate section where you can see various kinds of migratory birds, depending on the season of your visit. Along with all this, the place also has a unique crocodile breeding farm, which is', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(111, 'Birla Mandir', 10, 'Set in a oasis of green, Birla Mandir in Jaipur is a beautiful respite from the hustle bustle of city life. Take a walk around the splendid gardens or spend some quiet time soul searching when you visit the place, or simply let the splendid architecture take your breath away! Built completely in shining white marble, this temple also has carvings of deities from other religions, spreading the message of brotherhood and harmony among mankind.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(112, 'Sisodia Rani Palace and Garden', 10, 'Sisodia Rani Palace and Garden is a beautiful palace garden lying 6 km from Jaipur city which was built by Maharaja Sawai Jai Singh II in 1779 . It consists of tiered multi-level gardens with fountains, watercourses and painted pavilions along with a charming double storeyed palace that occupies the top terrace of the garden.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(113, 'The Monsoon Palace', 11, 'The Monsoon Palace, also known as the Sajjan Garh Palace, is a hilltop palatial residence. The history of the palace reflects the history of the Mewar kingdom. The palace, built with white marble, is located on Bansdara peak of the Aravalli hill range. The Royal family also used this building as a hunting lodge.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(114, ' ranakpur temple', 11, ' An important pilgrimage centre for the Jain, Ranakpur is cut off from the mainstream tourism in Rajasthan. The temple here is dedicated to Adinatha, the first of the 24 T?rthankaras in Jainism. It is a standing example of the craft of the Indian artisan and stone sculptor, with intricacy and detail unseen and unheard of. The delicate carvings on the 1444 pillars of this temple are all different from each other.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(115, 'Gulab bagh', 11, 'Once, this beautiful garden was regarded as one of the largest urban parks in India. Till date, the garden has not lost its charm. Tourists from all over come to visit this spectacular park of 19th century. It is actually a paradisiacal pleasure and one of the best gardens of Udaipur, Rajasthan.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(116, 'Lake Pichola', 11, ' Lake Pichola,which is at a walking distance from Gulab Bagh. The lake is a real treat due to the amazing buildings that dot its bank. The four islands within the lake house heritage hotels and temples. The pristine blue waters of the lake leave a soothing impact on the spectator. At the time sun-set, a boat ride in this lake is sufficient to enthrall anyone. ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(117, 'Ahar Museum', 11, 'Located about 2 kms east of Udaipur is an impressive cluster of cenotaphs of the Maharanas of Mewar. There are about nineteen cenotaphs of Maharanas cremated there.  display is limited but there are  very rare earthen pottery. Some sculptures and other archaeological finds. Some pieces date back to 1700 BC and a tenth century metal figure of Buddha is a special attraction. ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(118, 'Taj Lake', 11, 'The lake is a real treat due to the amazing buildings that dot its bank. The four islands within the lake house heritage hotels and temples. The pristine blue waters of the lake leave a soothing impact on the spectator.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(119, 'Jag Mandir Palace', 11, 'It is also called the "Lake Garden Palace".  The three-storied Palace is a palatial structure made in yellow sandstone and marble. In Jag Mandir Palace, Gul Mahal catches the major attention as this is the place where Prince Khurram lived with his family. Gul Mahal is made in the Islamic style of architecture.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(120, ' Bagore ki Haveli', 11, ' Bagore ki Haveli  portrays the mural paintings of Rajasthan designed in Mewar. The palace has more than a hundred rooms that display different costumes of the royal kings, The haveli is also famous for its fine mirror work and traditional dance shows of Rajasthan. While strolling in the Haveli, one can see the bath rooms, dressing rooms, bed rooms, living rooms and recreational rooms of the royal ladies as well. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(121, 'Fateh Sagar lake', 11, 'Fateh Sagar is an artificial lake that was constructed by Maharana Fateh Singh to the north of Pichola Lake in 1678. Situated to the north-west of Udaipur, the lake is considered to be the pride of this ''City of Lakes''.\r\n\r\nOne of the four lakes of the city, its blue waters and the backdrop of green has given the nickname of ‘second Kashmir’ to the city. Three small islands are located within the confines of the lake.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(122, 'The city palace', 11, 'The city palace is a beautiful construction from the era of the royals in Rajasthan.This palace might be one of the largest of its kind with intricately carved archways and delicate architecture. Located with the picturesque backdrop of rugged mountains, beside the Pichola lake on its shore, the city palace complex painted in gleaming white color has been compared to the Greek islands, such as the Mykonos.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(123, 'Jagdish temple', 11, 'Dedicated to the preserver of the universe, Lord Vishnu, the Jagdish Temple stands in the City Palace complex. While two elephants will greet you at the doorway, you will find an idol of the half man-half eagle Garuda after the first flight of stairs. Famous for its intricately carved pillars and doorways (you will find 50 on both its floors, each with unique carvings), the main shrine of this temple houses a massive four armed image of Lord Vishnu.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(124, 'Swaroop Sagar', 11, 'Connected to the Pichola and Fateh Sagar Lake, the Swaroop Lake is a picturesque little artificial water body created to serve as a water source for the Udaipur locals.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(125, 'Saheliyon ki bari', 11, 'Constructed by Maharana Sangram Singh in the 18th century to please his little princess, Saheliyon ki Bari is a stunning symbol of the grandeur of the emperors of Rajasthan. In her childhood, the princess demanded rain in the middle of the scorching heat and the king sanctioned the construction of Saheliyon ki Bari, a garden of rhythmic fountains and Lilly ponds. \r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(126, ' Moti Magri ', 11, 'Moti Magri overlooks the Fateh Sagar Lake in the city of Udaipur, Rajasthan.\r\nAtop the Moti Magri or Pearl Hill is the memorial of the Rajput hero Maharana Pratap, which has a bronze statue of the Maharana astride his favourite horse "Chetak".\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(127, 'Sukhadia circle', 11, 'A huge round about in the heart of the city which features a pond and a massive three tiered fountain, the Sukhadia Circle is a hub of entertainment for the residents of Udaipur. Head to the gardens here for some energy filled evenings where you can enjoy camel rides, horse tonga rides and boating, munch on the yummy street food available here or play an outdoor game or two with your kids. The lighting of the fountain gives it a fantastical quality in the nights, which is one thing you would lov', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(128, ' Vintage Car Museum', 11, 'Housing the car collection of His Highness, the Maharaja of Udaipur, the Classic Car Museum, affectionately called the Vintage Car Museum is surely going to mesmerise you. Watch all the grandeur associated with royalty come to life in front of your eyes at this museum where you will see an impressive collection of cars like the Rolls Royce Phantom, Cadillac, Mercedes and Austin Martin.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(129, 'Udai Sagar lake', 11, 'Constructed in 1559 by the founder of Udaipur, Maharana Udai Singh, the Udai Sagar Lake stands 13 km east of the city today. While a major part of its waters are used up by the zinc smelter close by, this lake is still visited by tourists for peaceful  views of sunsets. The setting sun gives the lake fiery hues of red, which probably reflect the historic tussle by the banks of this lake between Maharana Pratap and Man Singh which led to the Battle of Haldighati.', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(130, ' Shilpgram', 11, 'the Rural Arts and Crafts Complex. Spread over an undulating terrain of 130 bighas (70 Acres) of land and surrounded by the Aravallies, the Rural Arts and Crafts Complex is conceived as a living enthnographic museum to depict the lifestyles of the folk and tribal people of the West Zone. Within this complex, huts of the member states are constructed incorporating traditional architectural features of different geographical and ethnic groups residing within the West Zone of India comprising of fi', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(131, 'Eklingji temple', 11, 'Situated 22 km to the north of Udaipur, Eklingji Temple is one of the most famous temples of Rajasthan. An imposing structure with a pyramidal roof and intricate carvings in stone, the Eklingji Shrine houses a magnificent four-faced idol of Lord Shiva. This black marble sculpture is over 50 feet in height and the four faces are recognized as that of Lord Brahma, Lord Vishnu, Rudra and Surya.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(132, 'Sas Bahu temple', 11, 'With a tongue-in-cheek name like that, this one is bound to catch your attention. Though this temple is no longer functional, it is totally worth the visit for its sheer architectural beauty. Old stones slowly losing their colour to the trials of time and housing tranquility in the grooves of their age old carvings characterise this two temple complex. ', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(133, ' Haldighati', 11, 'Haldighati is a mountain pass in the Aravalli Range of Rajasthan in western India. It connects Rajsamand and Pali districts, 40 kilometres from Udaipur. The name is believed to have come from the turmeric-coloured yellow soil (Turmeric is haldi in Hindi).\r\nThe mountain pass is historically significant as the location of the historic Battle of Haldighati, which took place in 1576 betweenRana Pratap Singh of Mewar and Raja Man Singh of Amber, general of the Mughal emperor Akbar.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(134, 'Shrinathji Temple', 11, 'Shrinathji Temple is a hindu temple dedicated to Shrinathji in Nathdwara. It is considered an important pilgrimage centre by Vaishnavs. The temple has been designed in the lines of temple of Nanda Maharaj (Krishna’s father), in Vrindavan. Therefore, it is also known as Nanda Bhavan or Nandalaya (the House of Nanda).', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(135, 'The Rajsamand Lake', 11, 'The Rajsamand Lake is one of the most popular natural attractions of Rajsamand Town, situated on the way to Kumbhalgarh. This lake was built by Rana Raj Singh in the year 1660. On the southern end of this lake lies a large marble embankment, known as Nauchowki or the nine pavilions. This embankment has marble terraces and stone steps touching the lake and is dotted with five toranas or weighing arches and chhatris. At the time of sunset, the water of this lake glitters and appears orange', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0),
(136, 'The Dwarkadheesh Temple', 11, 'The Dwarkadheesh Temple , situated in Kankroli village, is among the most important temples of the Vaishnavas and the Vallabhacharya sect. The temple is similar in architecture to Shreeji ki Haveli and has a red stone idol of Dwarkadheesh Shri Krishna. This idol is believed to have been brought here from Mathura.\r\n', '', '', 'assets/images/manali/vashishta-hot-springs/img1.jpg', '', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
